Fix a type error in the MTU evaluation
To avoid the following error since required_mtu is int:
TypeError: argument of type 'int' is not iterable

Closes-Bug: #1973838
Change-Id: I36796018a537e6030bf46f283f1c74ef1fe4772c